### ISSUE TITLE
[feature request] Export of patient names and e-mail addresses

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#102]
In order to create general mailings to a group of patients it would be very handy to have the option to export a (csv/excel) list of patients (e.g. in a certain track), not only for superadmins but also for local admins. This would need a filter on the current export in which respondent id and other sensitive fields are omitted in the export. So just first_name, surname_prefix, last_name, gender	and e-mail address.

**Comment by mddejong** [comment]
Basic export of patient data is already possible. If export needs to be refined, specific issue should be made for that.
