### ISSUE TITLE
[Enhancement] Show automatic mail job: view depending on processing method

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#105]
When looking at "Show automatic mail job", and the processing method is "Send one mail per patient, mark all checked tokens as sent.", all tokens are shown anyway although they are not all sent (but they will be marked "sent" by the processing method, that is why they are shown). This leads to misunderstandings by users.
An alternative view might help, where in this setting only the first token would be shown, preferably with the number of tokens that will be marked as sent. 
Similarly, the less used option "Send one mail per patient, mark only mailed tokens as sent." should show only  tokens that are to be mailed (and to be marked "sent"). (This might already be so)

**Comment by mennodekker** [comment]
Solved by adding a preview functionality, also opened issue #148 for dicussion to further improve the screen
