### ISSUE TITLE
Warnings for surveys

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#110]
On synchronise surveys, we want to show more warnings about the survey. For example, not automatically loading end url, some optional settings, possible issues with question (equation questions that do not start or end with a curly brace) etc.

This would lead to a lot of warnings, so adding a new field to the survey table for warnings seems the best solution.

**Comment by mennodekker** [comment]
Linked to #75

**Comment by mddejong** [comment]
We need to enable search on the warnings
