### ISSUE TITLE
Slash in PID can break application

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#112]
There no validation on patient number, so when entering a slash it will break the urls.

Proposed solution is to add alphanum validation.

To be discussed if this breaks currently known implementations.

**Comment by mennodekker** [comment]
Some projects use a dash so just alphanum will break

**Comment by mennodekker** [comment]
Maybe filtering url unsafe chars like % & / is a better option

**Comment by mddejong** [comment]
Lijkt me de oplossing.


Met vriendelijke groet,
Matijs de Jong

M +31 (0)6 21 543221
T +31 (0)10 8910902
F +31 (0)84 7131153
