### ISSUE TITLE
[Enhancement] After adding a track to patient, open the show patient screen, not show track

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#121]
After a track is added to a patient, at present the show track screen is opened. For many users this is to much information and can be confusing, it would be better to return to the show patient screen.
A solution in event code could also work (e.g. Event – Track – AfterSave).

**Comment by mennodekker** [comment]
Implemented in ErasmusMC layer, do we change it for all or not?

**Comment by mennodekker** [comment]
Discussed in a meeting: we will wait for the Pulse user review to see if they want this in or not.

**Comment by mddejong** [comment]
We decided that this is a per project issue so we\'' leave it like this for now.
