### ISSUE TITLE
Stata / xml export fails

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#127]
all exports (Excel/csv/SPSS) work, but STATA (xml) generates a communication error

**Comment by jvangestel** [comment]
It probably also creates a php error in Setup / Project setup / PHP Errors. Could you supply that as well?

**Comment by roelfaber** [comment]
No php errors logged, sorry.

**Comment by jvangestel** [comment]
The stata exporter has gotten a rewrite, can this be rechecked once the new version is in use?

**Comment by mddejong** [comment]
Export module was revised, probably also for csv (and Stata) issues fixed.
