### ISSUE TITLE
Overview by token does not refresh after filling in a token ?

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#132]
Screen: Overview - By token
Selection: select a round and survey, status=open, for all tracks, all fillers and all staff.
When answering a token the first reported error is : 'Token does not match. The provided token does not match the one in your session. Click here to start the survey.'
After this error is displayed the token can be filled in.
This repeats for every token in the selected list.
The proposed workaround is to refresh or click the green 'Search' button after each token is answered.

**Comment by mddejong** [comment]
needs additional tests to reproduce this issue.

**Comment by mddejong** [comment]
Closed due to no new cases
