### ISSUE TITLE
Answer display sorting order improvement

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#149]
When multiple answers are displayed, sorting is (probably) on round (measuring moment), but not on date/timestamp of answers. When more answers are (re)done in the same round the order is random as can be seen in the screenshot. Adding the answer date/timestamp to the sorting order could give the correct display.
![anwerdisplay_notsorted](https://cloud.githubusercontent.com/assets/1294838/25891525/a8e71dae-3571-11e7-93a9-e30289adb162.PNG)

**Comment by mennodekker** [comment]
Not really random, sort order is now: success, round order, valid from
I will update it to add completion date/time at the end
