### ISSUE TITLE
Maintenance mode not working as expected

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#171]
Expected maintenance mode to block all tokens from being answered, this is not the case.
1.8.1p3.

**Comment by roelfaber** [comment]
Also sending mailjobs was not blocked. And deactivating the database sources did not work, after a status check they were active again.

**Comment by roelfaber** [comment]
(issue not closed)

**Comment by mddejong** [comment]
Solved: you can complete your current survey but then you stop.

**Comment by mennodekker** [comment]
d7ada5bc7f3ee8df0ba9b9d3aca95bf86d8cf00f
