### ISSUE TITLE
Cron / maintenance monitor mail not sent

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#178]
The alert mail was not sent, an error was generated in the errorlog of the redhat/apache server.
Probably due to issues about rights on the generated temporary file.

**Comment by mddejong** [comment]
I do need something more to solve to this. E.g. the error message in question.

And if monitor.json cannot be created in var/settings, then this is not an issue but an error in server configuration as there are other reasons why var/ must be writable, including var/settings.

**Comment by mennodekker** [comment]
The cron job for mailing is executed as a different user than the webserver. Both users can write the directory, but when cron user creates the file, the webserver user can not delete the file.

Solution could be to use explicit group rights or something in that direction. Probably best to discuss this in the next meeting.

**Comment by mddejong** [comment]
Again this is an error in server setup and this is not fixable in the code.

**Comment by mennodekker** [comment]
In code you CAN set rights, and we have done that before so it is fixable in code. 
Also the maintenance mode turned out not to select any user due to a mismatch between id and name.

**Comment by mennodekker** [comment]
Maintenance mode monitor job will now correctly add the users.
New project has a dummy monitor.json to prevent errors.
To test: make sure in project.ini a default from is set for the monitor otherswise sending the message might fail.
