### ISSUE TITLE
Submitdate vs completion time

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#185]
Submitdate and completion time are both used but seem to refer to the same thing. I think we can change to one word to describe this.

We should also think if we need gems side token completion time or the survey side completion time since the one is copied to the other. It would be great if we can reduce complexity and confusion.

**Comment by mennodekker** [comment]
Do we need the datestamp field from limesurvey? If so, maybe a more descriptive name like 'date last action' is more accurate?

**Comment by mddejong** [comment]
Agreed on use of one term. Update of excisting projects should be addressed.
