### ISSUE TITLE
Uncompleted survey answer dates are used during track recalculation

### ISSUE THREAD

**Issue by mddejong** [GemsTracker/gemstracker-library#192]
If e.g. a next treatment date is correct, the old answer is copied to the new survey. The new survey is not completed until the Fill in button is used, but the copied date is still used in recalculating the track.

**Comment by mddejong** [comment]
We decided to use these dates only when the survey is completed

**Comment by mennodekker** [comment]
@mddejong please review if this is what was needed and close the issue or push a new commit.

**Comment by mddejong** [comment]
Menno's fix worked
