### ISSUE TITLE
Switching group retains errors on unauthorized pages

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#196]
When an admin switches to a group with less rights to test certain functionality, and before switching was e.g. on the export multiple survey answers, an error is generated. The only way to test export options of the other role is to switch back to the admin role and go to an authorized page, e.g. a patient screen. When switching to the lower rights role again, the export options are still generating the error and other (authorized) export options are blocked, because the previous selected path is still in memory.

**Comment by mennodekker** [comment]
Unable to fix, as it would erase memory for the user switching to a lower role introducing a new problem. As this is a admin only option, we can safely assume the user can be instructed how to handle.
