### ISSUE TITLE
[feature request] Add-on functionality

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#20]
**Reported by Roel on 1 Nov 2012 13:20**

**Version:** 1.5.6

Make it possible to implement specials like randomization modules, studynumber assigments etcetera as add-ons 

[Mantis Bugtracker #573](https://gemstracker.org/mantis/view.php?id=573)

**Comment by mddejong** [comment]
This has been implemented in 1.9.0 and was the reason it became a .0 version.
