### ISSUE TITLE
auto-assign relationfield to track

### ISSUE THREAD

**Issue by harmslijper** [GemsTracker/gemstracker-library#219]
Currently assignment of a relation to a trackfield needs to be done manually. Would be nice if this could be done automatically. Solution suggestion: When multiple relationfields and or relations matchting thru field code.

**Comment by mennodekker** [comment]
Discussed:

- When adding a track to a patient, we could allow inline (popup?) adding a relation that will be auto assigned to the position where the <add> button was used.
- After adding a relation we could forward to a screen where we ask what to do with this relation. (Suggest tracks with unassigned relation fields)

**Comment by mennodekker** [comment]
A new overview could als help identify empty relation fields and provide an easy way to match that to available relations.

**Comment by mddejong** [comment]
We have created the Survey Completion event Relations to enable this
