### ISSUE TITLE
Log out on answering survey

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#223]
Does anyone use this functionality?

It seems that when it is used at least the first survey answered is answered by the logged in user. This is not what is suggested on the screen.

If nobody uses it, we can just remove the checkbox. If one does or wants to use is, maybe we should fix the behaviour.

**Comment by mennodekker** [comment]
Nobody seems to use it, we decided to just hide the box and not remove the functionality in gemstracker (yet).

**Comment by mddejong** [comment]
I'll have to reimplement this feature as Maasstad is going to use it
