### ISSUE TITLE
Implement 2FA

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#237]
Two factor authentication is often requested. Implementing this will really help in getting the tool accepted.

My thougts are for now to implement it in two forms on the organization level: 

1. always require 2fa 
2. only require 2fa when outside the iprange that allows login without 2fa

To be discussed: Should the ip range be the same for access / no access?

**Comment by roelfaber** [comment]
My suggestion: option 1 if it is a database account, and option 2 if it is an external authenticated account outside the IP range.

**Comment by mennodekker** [comment]
https://www.codementor.io/slavko/google-two-step-authentication-otp-generation-du1082vho
https://github.com/PHPGangsta/GoogleAuthenticator

**Comment by harmslijper** [comment]
Would be good to be able to set 2fa according to group the person belongs to.
At group level IP ranges are defined also.

**Comment by roelfaber** [comment]
maybe google (use my google account) or surfconext could also be of use, see #66 .

**Comment by mennodekker** [comment]
https://github.com/ChristianRiesen/otp

**Comment by mddejong** [comment]
<img width="551" alt="user validation flow" src="https://user-images.githubusercontent.com/13658302/38890015-8426f3b4-4280-11e8-9704-5a2fed43afc1.png">
A first attempt to flowchart the workings.

**Comment by mennodekker** [comment]
Passwordchecker -> maxAge depends on the user object and its ispasswordresetrequired setting. This does not work anymore.

**Comment by mennodekker** [comment]
Wish: Only allow to activate 2 factor when a valid response code is provided to prevent people from locking themselves out.

**Comment by mennodekker** [comment]
Impossible to break out of password reset loop (i want to logout and try another user)
