### ISSUE TITLE
[security] Staff acceptance of site conditions

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#24]
**Reported by Matijs on 14 Feb 2013 15:39**

**Version:** 1.5.7

Make it an option to require users to press OK (or Cancel) to accept the site usage conditions.

This may be required for NEN 7510 acceptance

[Mantis Bugtracker #582](https://gemstracker.org/mantis/view.php?id=582)

**Comment by mddejong** [comment]
As far as I know this is not a NEN requirement.
