### ISSUE TITLE
Composer warning about ambiguous classes when generating optimized autoload files

### ISSUE THREAD

**Issue by jvangestel** [GemsTracker/gemstracker-library#254]
When running "composer update -o" to create a classmap for composer optimization in production, the double Zend classes found in classes/Zend generate a warning:

`
Warning: Ambiguous class resolution, "Zend_Translate_Adapter" was found in both "/test/vendor/zendframework/zendframework1/library/Zend/Translate/Adapter.php" and "/test/vendor/gemstracker/gemstracker/classes/Zend/Translate/Adapter.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Db_Statement" was found in both "/test/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php" and "/test/vendor/gemstracker/gemstracker/classes/Zend/Db/Statement.php", the first will be used.
Warning: Ambiguous class resolution, "Zend_Pdf_Parser" was found in both "/test/vendor/zendframework/zendframework1/library/Zend/Pdf/Parser.php" and "/test/vendor/gemstracker/gemstracker/classes/Zend/Pdf/Parser.php", the first will be used.
`

Are these files still used? Are we sure these versions get loaded at the moment?

**Comment by mennodekker** [comment]
I can confirm the warnings. 

I think the classes are still needed. Beacuse of the warnings I never use the optimized classmap so not sure what happens. If the duplicates do not get loaded, we might have a problem as they are low-level files in the zend framework. Replacing them might mean that we need to change a lot of classes in the chain.

**Comment by mennodekker** [comment]
When reviewing the changes in the classes to their original ones, we should document the changes in the header of the file so we can easily identify them in the future.

**Comment by jvangestel** [comment]
I've added a test function to both Zend_Translate_Adapter files. When I try that test function in a Gems controller on $this->translateAdapter->test() it clearly loads the wrong Zend_Translate_Adapter.

So currently the duplicates are NOT loaded.

**Comment by mennodekker** [comment]
- [ ] https://github.com/GemsTracker/gemstracker-library/classes/Zend/Pdf/Parser.php
- [ ] https://github.com/GemsTracker/gemstracker-library/classes/Zend/Db/Statement.php
- [ ] https://github.com/GemsTracker/gemstracker-library/classes/Zend/Translate/Adapter.php
