### ISSUE TITLE
Requiring dev-master of MUtil will load newest MUtil in any version upgrade

### ISSUE THREAD

**Issue by jvangestel** [GemsTracker/gemstracker-library#255]
Since 6 September we require MUtil version dev-master, instead of a specific version.
When you currently update a 1.8.2 project, it will load MUtil 1.8.3. While this isn't really a problem with the current version, it might bring unexpected results in future updates.

Is there a specific reason besides easier releases that the version isn't locked anymore?

**Comment by mennodekker** [comment]
The release branch (r1.8.3) has a version ^1.8.3 and allows all below 2.0.0
This should be ~1.8.3, which allows all below 1.9.x
The constraint <1.8.4 is the safest I think.

We could do an update for 1.8.2 and 1.8.3 branches and do a new patchlevel release to fix this?

The master should always allow any version as it is the development branch and should be able to match with unreleased changes in MUtil.

**Comment by mennodekker** [comment]
1.8.3 has requirement <1.8.4
