### ISSUE TITLE
show available languages for surveys

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#277]
In the screen 'trackbuilder - surveys - showing survey' no information is available about the languages that are available for the survey. It would be nice to show here in which languages a survey is available.

**Comment by jvangestel** [comment]
getLanguageDescription doesn't seem to be used. If it is, or will be used, could it be refactored in a separate class? Maybe a TranslateLanguage class or something?

**Comment by mennodekker** [comment]
getLanguageDescription was removed in cb43db1 (linked to the wrong issue)
