### ISSUE TITLE
System should be aware of partially answered tokens

### ISSUE THREAD

**Issue by mddejong** [GemsTracker/gemstracker-library#280]
In the compliance overview the difference between partially answered and not answered should be clear

The buttons for the token screen should be labelled clearly

**Comment by mennodekker** [comment]
When using redo the token should be marked as 'partial'

**Comment by mennodekker** [comment]
Answer displays should also show the status icons

**Comment by mennodekker** [comment]
Export button is now missing for some of the overviews (at least for overview-plan)
