### ISSUE TITLE
Deactivated users and mailjobs

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#290]
When a user is deactivated, he could still be in use for mailjobs:
 - as the sender (for logging)
and / or
 - as the provider of a sender email address

While both still function when the user is deactivated, it shows some visual glitches:
 - The comm job overview shows the userid instead of the name
 - Editing the job shows no name, unable to select the user

What to do?
 - Check if userid is in use for mailjobs on deactivation?
 - Show the deactivated user (maybe strike-through?)
 - Other options?

**Comment by mddejong** [comment]
Add the disabled users already in mail jobs to the list?

Met vriendelijke groet,
Matijs de Jong

M +31 (0)6 21 543221
T +31 (0)10 8910902
F +31 (0)84 7131153

**Comment by mddejong** [comment]
After revisiting this issue I decided that the current behaviour is the desirable one as:
- the sending of mail keeps functioning, even when the user is disable,
- the mailjob interface clearly shows something is wrong,
- when editing the job, the user is required to correct it
