### ISSUE TITLE
[feature request] Importeren van data uit apparaten

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#3]
**Reported by anonymous on 20 Apr 2010 11:02**

**Version:** 1.1

Het moet mogelijk zijn om met een bepaalde interface data uit een meetinstrument in te lezen als survey response in Pulse.

[Mantis Bugtracker #2](https://gemstracker.org/mantis/view.php?id=2)

**Comment by mennodekker** [comment]
**Comment posted by harm on 21 Apr 2010 14:13**

Heb met Jan gesproken van E-link. Gaat proberen een export functie te regelen naar standaard txt (of xml) file met meetresultaten. Zou dan een optie zijn in PULSE, of invullen via Lime survey of import van gegevens via die exporteerde file.

**Comment by mennodekker** [comment]
**Comment posted by harm on 11 Feb 2011 09:53**

Ga met Diak mensen overleggen waar het kenmerk in te vullen zodat een directe upload naar LS database mogelijk wordt. Specificatie van datafile volgt nog.
Voorlopig voorbeeld scherm en datafile al attached.

**Comment by mennodekker** [comment]
**Comment posted by Matijs on 16 Oct 2014 11:22**

Dit feature houdt in dat er op patient en kenmerk niveau Import knoppen komen waarmee antwoorden voor 1 patient of kenmerk geimporteerd worden.

**Comment by mennodekker** [comment]
**Comment posted by menno on 24 Aug 2016 09:02**

Closed by accident due to github issue reference

**Comment by mddejong** [comment]
I decided to close this item. 

The import of data as answers has been possible for a long time using Answer import and adjusting the import to the export of a specific export can be achieved using Import Transaltors.
