### ISSUE TITLE
Use the organization contact name in e-mail from

### ISSUE THREAD

**Issue by jvangestel** [GemsTracker/gemstracker-library#321]
In 2013 we disabled the Organization name <organization@email.com> style FROM because Windows Mail did not support it (I can't really find out what happened to E-mails back then, but it seemed severe enough to disable it in Gemstracker 474997bf6b2d10be3559dca715f51c81 ) 

Since Windows mail has been discontinued years ago, I wanted to discuss the idea of using the correct e-mail notation as default again, as it's much more user friendly

**Comment by mennodekker** [comment]
@jvangestel  Commit is not linked, can you point me to the right commit (date/time or description)?
