### ISSUE TITLE
[feature request] change Newproject to YourProject

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#33]
**Reported by Roel on 13 Feb 2014 13:40**

**Version:** 1.6.2

Just a name change that will make explanations easier and clearer.
Can be used simultaneously to add a lot of (commented) example code to this project, like creation of extra fields, changing views etcetera.

[Mantis Bugtracker #629](https://gemstracker.org/mantis/view.php?id=629)

**Comment by mddejong** [comment]
I declare this issues refused after 4 years. Let us just keep this in mind for FT 2.0
