### ISSUE TITLE
Lessen query load from auto search

### ISSUE THREAD

**Issue by mddejong** [GemsTracker/gemstracker-library#340]
When automatically searching a new request is sent for every query-changing input, while the old query is cancelled. 

By waiting for the previous query to finish before sending any new query the number of queries drops. This might result in less responsiveness. On the other hands on IIS and nginx servers the cancellation requests aren't processed, resulting in earlier queries sometimes returning data **after** a later query with a more limited result set returned data. On those servers the user experience will improve by handling queries sequentially.

**Comment by mennodekker** [comment]
gemstracker/gemstracker-template@ed8ad382fe59b6d9759a2fa619cc7b31381426bb

**Comment by mennodekker** [comment]
Closing the issue, i released the gemstracker-template as 1.8.6 so it will be included from now on without requiring the dev-master
