### ISSUE TITLE
[feature request] Survey meta data manager

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#36]
**Reported by Matijs on 25 Mar 2014 15:10**

**Version:** 1.6.3

So that we can say two LS questions give the same answer even if they pose a different question or have different codes / answer options.

[Mantis Bugtracker #654](https://gemstracker.org/mantis/view.php?id=654)

**Comment by mddejong** [comment]
Have not heard this request for 8 years.
