### ISSUE TITLE
Track builder: filter survey list

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#362]
When there are many surveys a filter for the track builder could be useful

- keep filter during session, defaults should show all surveys like it is now or a better reasonable alternative (filter like the survey overview: source, active, inactive etc.)
- when a filter excludes the current survey, make sure that does not introduce a problem

**Comment by roelfaber** [comment]
Maybe introduce a "use in track builder" option in survey settings, next to the "Active" setting. This path always allows re-entering a survey in the filtered list. And maybe add a toggle for this option at surveylist level, e.g. toggle all active surveys or all surveys from one source.

**Comment by mddejong** [comment]
There are a lot of search options these days, especially since #110, #277 and #603.
