### ISSUE TITLE
[feature request] Create appointments when a survey is answered

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#37]
**Reported by Matijs on 15 May 2014 15:22**

**Version:** 1.6.3

Use a date linked to a token or survey (or track?) to create an appointment in a patients agenda and optionally assign it to an appointment field in the track.

[Mantis Bugtracker #671](https://gemstracker.org/mantis/view.php?id=671)

**Comment by mennodekker** [comment]
**Comment posted by Matijs on 24 Apr 2015 12:49**

For 1.7.1 I created a Depar only solution, in 1.7.2 we ant to make it general using events with database stored paramteers

**Comment by mennodekker** [comment]
Note: When appointments are imported from another system, the appointment should probably not be made in GemsTracker but in main appointment application.
Could be a solution to use a create appointment event for this.

**Comment by mddejong** [comment]
This cannot be achieved except on a per project basis as long as we do not have a new way tp create evnts.
