### ISSUE TITLE
Add diagnosis as an appointment item

### ISSUE THREAD

**Issue by mddejong** [GemsTracker/gemstracker-library#375]
Store diagnosis (or DBC in Dutch) as a high level object to GemsTracker to appointments in a method similar to activities and procedures

**Comment by mennodekker** [comment]
@mddejong If this can not be closed yet, please set milestone to 1.8.6

**Comment by mennodekker** [comment]
@mddejong can this one be closed for 1.8.6?

**Comment by mddejong** [comment]
Cl;osed for now
