### ISSUE TITLE
[bug] Using copy & paste of templates scrambles url's

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#38]
**Reported by Matijs on 23 May 2014 09:35**

**Version:** 1.6.3

When copy and pasting formatted text in the teamplate editor the url&#039;s can end up scrambled. E.g.:

[url={token_url}]deze link[/url]

changes into

[url=https://depar.ciceroreumatologie.nl/comm-template/edit/id/%7Btoken_url%7D]deze link[/url]

These cases are quite recognizable as they always contain %7b and end with %7D.

The code should fix these fields so they revert back to the original {token_url}. This is of course also the case for other url fields.

[Mantis Bugtracker #678](https://gemstracker.org/mantis/view.php?id=678)

**Comment by mennodekker** [comment]
**Comment posted by jvangestel on 5 Jun 2014 17:34**

This is something that CKEditor does. (it changes it when you press the source button, before that, it seems fine). Thus far I have no luck with finding out why it changes the URL to an absolute path. In a separate CKEditor install (same version) I can&#039;t seem to reproduce the issue.
I&#039;ll look into this more, to see if plugins or a version upgrade might help.

in worst case it can be fixed dirty by changing the url on save.. But that might still result in uncertain results.

**Comment by mennodekker** [comment]
**Comment posted by jvangestel on 6 Nov 2014 16:57**

After updating CKEditor, this bug is still persistant. I have found it&#039;s a bug in the BBCode plugin and have submitted it to the CKEditor bugtracker.

**Comment by mennodekker** [comment]
**Comment posted by jvangestel on 27 Nov 2014 15:04**

The Issue has been accepted. So this will have to wait until someone picks it up and fixes it.
http://dev.ckeditor.com/ticket/12638

For now I&#039;ll move it to 1.6.6 in the hope it has been fixed by then.

**Comment by mddejong** [comment]
I have not had this error for a long time so it's time to close it.
