### ISSUE TITLE
track import is not logged

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#382]
In log settings: track-maintenance.import - log data change is on, but import action does not appear in the log (v1.8.5)

**Comment by mennodekker** [comment]
Merge:
https://github.com/GemsTracker/gemstracker-library/blob/b072e42748dacb3eafd19ee9cd3054437c22edcc/classes/Gems/Tracker/Snippets/ImportTrackSnippetAbstract.php#L485-L496

Import:
https://github.com/GemsTracker/gemstracker-library/blob/b072e42748dacb3eafd19ee9cd3054437c22edcc/classes/Gems/Tracker/Snippets/ImportTrackSnippetAbstract.php#L295-L306

ModelImport:
https://github.com/GemsTracker/gemstracker-library/blob/b072e42748dacb3eafd19ee9cd3054437c22edcc/classes/Gems/Snippets/ModelImportSnippet.php#L38-L63

**Comment by mennodekker** [comment]
Maybe also log the track txt file like we do for other imports? Seems they are not logged now.
