### ISSUE TITLE
Provide an unsubscribe option for participants

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#386]
We should implement an unsubscribe possibility to allow people to get the no email flag on the current track or on person record. Think abotu who we should inform about this change (organisation contact email?)

**Comment by mennodekker** [comment]
There are a lot of scenario's, for now it seems best to:
- make a field that can be inserted in the email with the link (this should also add the header to the email!!). 
- use token in the link, and ask to enter the email in the landing page, the next page can show current tracks and name
- maybe even require the user to click a 24 hour valid link in his email to confirm the unsubscribe
Make all emails (to respondent and organisation) changable via the mail template screen.

**Comment by mddejong** [comment]
This was solved in 1.8.7
