### ISSUE TITLE
"Track" trackfield is given as option but no TrackField exists

### ISSUE THREAD

**Issue by jvangestel** [GemsTracker/gemstracker-library#393]
in Gems\Tracker\Model\FieldMaintenanceModel:r479 'track is supplied as an optional field, but no Gems\Tracker\Field\TrackField exists.

Probably someone forgot to add a file to git?

**Comment by mennodekker** [comment]
https://github.com/GemsTracker/gemstracker-library/blob/d8aba84490b1097dee7987319aa9095a2ee60f6f/classes/Gems/Tracker/Model/FieldMaintenanceModel.php#L458-L484

Maybe it was intended to be used for linking tracks to eachother?

**Comment by jvangestel** [comment]
The actual Field code did not exist yet, but the field type was already committed

**Comment by mennodekker** [comment]
Maybe exclude the current track in the selectionlist? 
Calulate fieldinfo now shows the trackid, maybe it's better to show nothing or the name of the track.

**Comment by mennodekker** [comment]
e25b3a3
