### ISSUE TITLE
Get Track information from RespondentTrack with less load

### ISSUE THREAD

**Issue by jvangestel** [GemsTracker/gemstracker-library#398]
If you use the tracker to get all ResponentTracks ( \Gems_Tracker->getRespondentTracks() ), the gems__track information is already added in each RespondentTrack.
If you ask for the Track code in RespondentTrack ( \Gems_Tracker_RespondentTrack->getCode() ) No check is done if the field is actually already available, but the track is loaded separately.
Wouldn't it be better to check if gtr_code is already set in the _respondentTrack array? It would cost you 1 less database query to get that info. 
We could ensure the data is there and add a few other fields, like track name or track active.

Are there any objections in doing it this way?

**Comment by mennodekker** [comment]
Go ahead, seems like a good plan to me.
