### ISSUE TITLE
[feature request] Create new survey source(s) for showing results in a track

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#41]
**Reported by Matijs on 8 Jan 2015 14:50**

**Version:** 1.7.0

E.g. make it so that patients see the requirements, get the right personal page, get a report about theit progress, etc...

[Mantis Bugtracker #727](https://gemstracker.org/mantis/view.php?id=727)

**Comment by mddejong** [comment]
This has been implemented on a per project basis.
