### ISSUE TITLE
When a model has a transformer, datetimes become null in the after save data

### ISSUE THREAD

**Issue by jvangestel** [GemsTracker/gemstracker-library#410]
When a model with a transformer, e.g. RespondentTrackModel gets saved, the row gets filtered through _filterDataForSave for a second time. 

https://github.com/GemsTracker/MUtil/blob/13d2a1e1a6327927cccdf5806bef18fb93dac1b1/src/MUtil/Model/ModelAbstract.php#L1815-L1819

Since the datetime fields returned are in the storage format and not in the display format, the formatSaveDate in MUtil_Model_DatabaseModelAbstract NULL's the date, since \MUtil_Date does not throw an exception, but returns null.
The code in the catch in that fucntion should also be run if the \MUtil_Date::format returns null

https://github.com/GemsTracker/MUtil/blob/13d2a1e1a6327927cccdf5806bef18fb93dac1b1/src/MUtil/Model/DatabaseModelAbstract.php#L816-L818

```php
try {
    $date = \MUtil_Date::format($value, $saveFormat, $displayFormat);
    if ($date === null && \Zend_Date::isDate($value, $saveFormat)) {
        return $value;
    }
    return $date;
}
```

The fact that dates get null'ed after save causes the transforms of that model dependent on that date to not work correctly (For instance in the RespondentTrackModel, Appointment fields do not calculate correctly after initial save)

Does everyone agree on the fix? Should it be applied to r1.8.5 as well, and would it be enough to unit test DatabaseModelAbstract->formatSaveDate?

**Comment by mennodekker** [comment]
I think the main bug here is that _filterDataForSave should only run once. When looking into the flow I see that the transformer's triggeronsaves  method makes the onsave run AFTER the data is saved. I don't see why this should happen. A clear flow of before save, proces onsaves, actual save and after save provides more than enough complexity and handles to change behaviour. 

The only transformer i found that uses triggeronsaves = true is the addTrackFieldsTransformer

Also strange: the save method checks if there is a load transformer, or there are dependencies and then runs the processRowAfterLoad. A transformLoad  for the transformer will not be triggered.

https://github.com/GemsTracker/MUtil/blob/13d2a1e1a6327927cccdf5806bef18fb93dac1b1/src/MUtil/Model/ModelAbstract.php#L1971-L1984

**Comment by mennodekker** [comment]
@jvangestel Can you explain where this happens or maybe write a unit test to expose the problem?

**Comment by mennodekker** [comment]
@jvangestel can you verify that:

- [ ] this fixes your problem
- [ ] this does not break other things

I intend to release this in 1.8.6-p1 or 1.8.7 not in the current 1.8.6

**Comment by mddejong** [comment]
As this has been working for a while now and a visual check of the code seems to confirm the correct workings, I'm closing this issue.
