### ISSUE TITLE
[documentation] Limesurvey info to keep in mind

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#43]
**Reported by menno on 12 May 2015 06:43**

Starting with version 2.06 LimeSurvey will have case sensitive tokens
https://github.com/LimeSurvey/LimeSurvey/commit/086dfa7ac714a52a3ff19fb9e2be18e93f7015ee

https://bugs.limesurvey.org/view.php?id=9470

[Mantis Bugtracker #744](https://gemstracker.org/mantis/view.php?id=744)

**Comment by mennodekker** [comment]
**Comment posted by menno on 24 Feb 2016 14:22**

Version 2.5 and up require mysql 5.5.3 because of the new utf8mb4 collation

**Comment by mddejong** [comment]
Works at the moment
