### ISSUE TITLE
Email with & can not be entered

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#431]
Email with an ampersand like tom&jerry@wb.com is a valid email, but is is not accepted in the UI or via import.

This is not very common, but we do have a few of these emails.

**Comment by mennodekker** [comment]
For mailto links it should be url encoded to %20

**Comment by jvangestel** [comment]
Is part of the problem of it failing validation? Have you tried using the filter_var in php as validation? We have a validator that uses it in Pulse. Pulse_Validate_SimplePhpEmail, because some other emails would fail validation as well with the built in Zend one

**Comment by mennodekker** [comment]
@jvangestel  For me the notags validator was the problem
