### ISSUE TITLE
Add a database dump option that creates a dump without patient information

### ISSUE THREAD

**Issue by jvangestel** [GemsTracker/gemstracker-library#435]
For development, testing and project copying purposes it would be nice to be able to easily make a database dump without respondent or account data.

**Comment by jvangestel** [comment]
Added code that does this for Gemstracker specific.
It takes all tabels in Gemstracker and can create a mysql dump from it. Currently hardcoded are the tables that are safe to export as they do not contain any sensitive data.
The mysqldump file gets stored in a specific folder, but currently is not downloadable in the interface.
In some environments it can be safer to call this controller on the commandline, as it can take a while to process.

Possible improvements:
- Possibly add the whitelist of non-respondent data to a table or as prefix comment to the sql files.
- Add something similar for limesurvey sources.
- Maybe a separate option to whitelist staff accounts?
- Add option for compression (e.g. gzip the .sql output)
- Possibly add other options from the [mysqldump-php library](https://github.com/ifsnop/mysqldump-php)

**Comment by mennodekker** [comment]
@jvangestel Dit is de foutmelding:
Notice: Undefined index: type in classes/Gems/Default/DatabaseBackupAction.php on line 68
Notice: Undefined index: name in classes/Gems/Default/DatabaseBackupAction.php on line 71
Notice: Undefined index: name in classes/Gems/Default/DatabaseBackupAction.php on line 73
mysqldump-php error: Table () not found in database

Ik heb de vinkjes voor respondent data en views niet aan staan, maar er zitten wel extra tabellen in deze database die niets met GemsTracker te maken hebben.

**Comment by mennodekker** [comment]
Het is de gemsdata tabel die leeg wordt gemaakt en dan met alleen exportTable en respondentData in het model komt.
https://github.com/GemsTracker/gemstracker-library/blob/2a234be6d0e29e80bf2d78cedc0fead7b574187b/classes/Gems/Model/ExportDbaModel.php#L81

**Comment by jvangestel** [comment]
Dus een continue na de unset op r82 zou het moeten fixen?

**Comment by mennodekker** [comment]
Even gecontroleerd, ik krijg nu geen foutmelding meer.

**Comment by mennodekker** [comment]
68b938e

**Comment by mennodekker** [comment]
Changing the options does not do anything, database dump stays at 'no respondent data'.

For 'no data' tables the drop / create destroys existing data. This includes other tables in the same database, like limesurvey, wordpress etc. Better would be to only export the tables that are allowed and forget about the others. Also when all tables get included, the export should only handle gems tables, possibly tables of related sources but no other tables.

**Comment by jvangestel** [comment]
Changing options was not working due to autoFilterAction not being included.

I have put a filter in place where only gems_ prefixed tables are added to the export, so a shared database will work. 

I've also added a better representation of which tables and data gets exported, that changes when you select include respondents.

The following options have also been added:
- Include drop tables (default selected): Include the drop table statements in front of every exported table
- Single transaction (default selected): Make the database export in a single transaction
- Lock tables: Lock the tables before exporting

Removing the empty respondent tables from the export, or making a whitelist/blacklist of tables/data or make them selectable at all seems out of the current scope.

**Comment by mennodekker** [comment]
@jvangestel I fixed some logic errors, I think it is fine for now. Did you remove the views on purpose? Not a big deal for me, just curious.

**Comment by jvangestel** [comment]
I see, sorry for not catching them!

I removed the views because they're not part of the gems__ group, which makes them hard to distinguish from other installed applications in the same database. Also since gems__data is currently not added to this dump, the current views we use do not seem very useful to add.

**Comment by mennodekker** [comment]
Ok lets leave the rest for the next version then. I will open an issue so all we can think of can be added there.
