### ISSUE TITLE
A generic solution for embedding in EPD without login

### ISSUE THREAD

**Issue by mddejong** [GemsTracker/gemstracker-library#478]
Integration of patients screens with EPD's increases GemsTracker acceptance. What is needed is a generic solution that can be easily adapted for project specific implementations, but that offers a basic framework for these implementations.

**Comment by mennodekker** [comment]
Right to _delete_ is not used, should be _deactivate_ / _reactivate_ 
Also add to the gems__roles table for new installations

https://github.com/GemsTracker/gemstracker-library/blob/d550dd12407aa038f497335ea0ba0e6e03cd1985/configs/db/patches.sql#L1547-L1549
https://github.com/GemsTracker/gemstracker-library/blob/d550dd12407aa038f497335ea0ba0e6e03cd1985/classes/Gems/Menu/SubMenuItem.php#L375-L405
