### ISSUE TITLE
New track is always inactive

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#480]
When creating a new track, the default for 'gtr_active' is 0 (inactive). In the create from this field is not visible so a user is unable to change it and must first save the track, then edit it to set it to active. This is cumbersome.

Proposal is to show the field, and leave the default to inactive.

**Comment by mddejong** [comment]
Make it so.

The idea was that you have to do work before you can activate a track, but that was before import and the use of track fields.
