### ISSUE TITLE
Duplicate method getSurveys

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#484]
DbLookup->getSurveys is a duplicate of TrackData->getSurveysFor

https://github.com/GemsTracker/gemstracker-library/blob/be04b05a4e66e5b5819e6a0bc2c247f4849f78dc/classes/Gems/Util/DbLookup.php#L594-L609

https://github.com/GemsTracker/gemstracker-library/blob/be04b05a4e66e5b5819e6a0bc2c247f4849f78dc/classes/Gems/Util/TrackData.php#L388-L403

**Comment by mddejong** [comment]
Looks like a function used in Pulse. I'll look into it.
