### ISSUE TITLE
[feature request] Self-rotating log files

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#49]
**Reported by Matijs on 20 Aug 2015 14:09**

**Version:** 1.7.1

GT logfiles grow and grow unless an external application cleans them up or an admin user throws the old  file away. A new system for logs keeping fiels per day on a monthly or yearly basis (with browse option when looking for the files in GT) would be a better solution.

[Mantis Bugtracker #763](https://gemstracker.org/mantis/view.php?id=763)

**Comment by mddejong** [comment]
For now we're using OS functionality for this.
