### ISSUE TITLE
Combine multiple excel export files as sheets in one excel file

### ISSUE THREAD

**Issue by jvangestel** [GemsTracker/gemstracker-library#515]
Instead of exporting multiple excel files, make each 'file' a sheet in a combined excel file

**Comment by jvangestel** [comment]
Added the ability as an excel option.

Combined with the more flexible multi model options added in 2a2edcf, you can add different models to one export.

Points for improvement:
- Unsure about performance in bigger files, or when a lot of files are added.
- Currently the option is visible to all exports, both multi and single file. This doesn't break export, but does give you a combined file with one sheet and the current export as sheet name

**Comment by mennodekker** [comment]
Catchable fatal error: Argument 1 passed to Gems\Export\ExportAbstract::getAnswerModel() must be of the type array, string given, called in vendor/gemstracker/gemstracker/classes/Gems/Export/ExportAbstract.php on line 624 and defined in vendor/gemstracker/gemstracker/classes/Gems/Export/ExportAbstract.php on line 524

**Comment by jvangestel** [comment]
This should fix the catchable error, apparently I didn't add the new version of getAnswerModel

**Comment by mennodekker** [comment]
Seems to work, codebook export is still broken.

**Comment by mddejong** [comment]
This works so I'll close it
