### ISSUE TITLE
Using zf1-future (php 7.2+)

### ISSUE THREAD

**Issue by jvangestel** [GemsTracker/gemstracker-library#550]
We decided to work with shardj/zf1-future to allow GT installations on PHP 7.2+.

In release 1.17 they have shifted focus to support only PHP 7.1+ instead of the earlier 5.4+.
If we want to keep supporting PHP <7.1 we can either lock the release to an earlier version, or revert back to zendframework as default, but overwrite to zf1-future in the composer.json of projects.

The addition of 
```json
"replace": {
    "zendframework/zendframework1": ">=1.12.20"
}
```
in the composer.json of zf1-future shard 1.14.1+ Makes it possible to overwrite on Project level. It also seems to halt installing version > 1.14 due to some constrains I can't seem to figure out (composer errors on update, when trying to force it to go higher).

The proposed idea thus is:
Make MUtil use "zendframework/zendframework1" for PHP 5.5, 5.6 and 7.0 support, and for 7.1 and higher use "shardj/zf1-future" in said projects.

**Comment by mddejong** [comment]
We are using this in standard GT en moving on in GT 2.x
