### ISSUE TITLE
Suggestion name inconsistency

### ISSUE THREAD

**Issue by Jbakx** [GemsTracker/gemstracker-library#558]
The name of track field filters is inconsistent. When you want to apply a track field filter to a certain track, you have to select the track field filter under the name "automatic link", which was very confusing to me.

![name inconsistency](https://user-images.githubusercontent.com/50862985/82201511-ca38ef00-9900-11ea-93dd-dc6c299b3746.png)

**Comment by mddejong** [comment]
Fixed in commit 4f6d8fd91a56d73485611036fb200c8cdd07aaab
