### ISSUE TITLE
[feature request] Add track, patient and consent fields to track fields

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#56]
**Reported by Matijs on 3 Sep 2015 14:04**

**Version:** 1.7.1

Add fields that contain links to prior or later or any other track of the same patient. Add fields containing consents and fields containing patient  information - either at track start or constantly updated.

[Mantis Bugtracker #771](https://gemstracker.org/mantis/view.php?id=771)

**Comment by mddejong** [comment]
Several of these issues have by now been solved including consent fields
