### ISSUE TITLE
Allow filtering in mailjobs on a specific relation

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#572]
Different relations might require a different email template, for example teachers and parents. To facilitate this a filter for 'filler' like in the overviews could be added.

**Comment by mennodekker** [comment]
In the current implementation the list is not filtered for staff, patient or relations so impossible selections could be made. This is left for a future update if desired.

**Comment by roelfaber** [comment]
If the (e.g. age 5-7) survey is valid e.g. 4 weeks before the appointment, and the birthday is three weeks before the appointment, the 5-7 survey is still valid.
So the moment the token is activated is the moment used for calculating age and validity of rounds.
