### ISSUE TITLE
Appointment changes can affect conditions

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#590]
**Situation:**
Token is based on an appointment and has an age condition.
Appointment is scheduled to a future date
Due to age condition, the round is skipped

**Problem:**
Now, when the appointment is updated, the skipped round will not be recalculated and the condition will not change.

**Comment by mennodekker** [comment]
@mddejong @jvangestel Please have a look, let me know if you see any problems or if it is unclear.

**Comment by mddejong** [comment]
Hmm looks legit to me. Maybe we should expand this for all non-succes reception codes. 

I think there is no downside to calculating dates on "rejected" but unanswered tokens.

**Comment by mddejong** [comment]
Took some concentration but seems to de the job for me. :)

**Comment by roelfaber** [comment]
Bug is resolved, correct working confirmed, with this comment.
If for a child of 7 years old the (e.g. age 5-7) survey is valid e.g. 4 weeks before the appointment, and the birthday is three weeks (or 27 days) before the appointment, the 5-7 survey is still valid also after the birthday and the child has become 8 years old.
So the moment the token is activated is the moment used for calculating age and validity of rounds.
