### ISSUE TITLE
multi-layer criteria for valid from / valid until calculation

### ISSUE THREAD

**Issue by Jbakx** [GemsTracker/gemstracker-library#592]
We would like to be able to use multiple criteria for the calculation of the valid from/valid until dates. 

**example**
For the intake questionnaires, we would like to set the 'valid until' date as the treatment date. However, the treatment date is not always available at the start of a track. Therefore, we had to set the 'valid until' date with track startdate + 3 weeks. Sometimes this leads to intake questionnaires still being available after treatment.  What we would like to do here is to set the 'valid until' date with track startdate + 3 weeks, unless the treatment date is available, then we want to use the treatment date as the 'valid until' date.

**Comment by mddejong** [comment]
We decided not to do this.
