### ISSUE TITLE
TrafficLight snippet round description grouping is case sensitive

### ISSUE THREAD

**Issue by jvangestel** [GemsTracker/gemstracker-library#599]
The round description grouping in the \Gems_Snippets_Respondent_TrafficLightTokenSnippet is casesenstive.
If for example you have 2 rounds with the following round description
- Intake
- intake

Two 'objecten' panels are created. Since the name in the header is always capitalized, it's hard to see why 2 rounds are created.

@mennodekker Is it intended that the grouping is case sensitive?

If not, https://github.com/GemsTracker/gemstracker-library/blob/3bf892684f3965ceb65ad48b85d4a884e45e80c3/classes/Gems/Snippets/Respondent/TrafficLightTokenSnippet.php#L648
could be changed to 
```php
$description = strtolower($row['gto_round_description']);
```

and https://github.com/GemsTracker/gemstracker-library/blob/3bf892684f3965ceb65ad48b85d4a884e45e80c3/classes/Gems/Snippets/Respondent/TrafficLightTokenSnippet.php#L679
could be changed to 
```php
$day->h5(array($summaryLink, ucfirst($row['gto_round_description'])));
```
to make sure any intended casing is not lost visually

**Comment by roelfaber** [comment]
This becomes a solution for what should be a selectable item in the round description, and that item should be defined once as timing or measurement moment in the track.
Maybe better to put effort in thinking how to solve the real problem?
The workaround is not to make mistakes in the round description by using copy-paste or correct this everytime these unwanted differences appear.
