### ISSUE TITLE
Add insertable survey only shows part of the title

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#602]
When adding an insertable survey to a patients track, the selection box only shows a small part of the survey title. Sometimes surveys only differ in their suffix and one cannot see which survey is selected. 
It would be nice if the hoover action or the i symbol would show the complete title.

**Comment by mddejong** [comment]
This problem is solved by issue #617, that replaces the dropdown for surveys with a multi checkbox.
