### ISSUE TITLE
Allow mailability to be set at multiple levels

### ISSUE THREAD

**Issue by mddejong** [GemsTracker/gemstracker-library#603]
Allow mailability to be set at multiple levels.

Currently mailable is set to yes or no. It should be possible to set multiple levels where patients still get e.g. anesthesia mail or mails they are legally required to answer, while they do not get the other mails.

**Comment by roelfaber** [comment]
Answer items not yet in translation? (input id="gr2o_mailable-100" Yes en input id="gr2o_mailable-0" No )
