### ISSUE TITLE
Adding an insertable survey to an emptied phase goes wrong

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#609]
Sometimes e.g. an agegroup specific survey is replaced by a survey for another age group, depending on patients mental status. If at that moment the original survey is removed first, and it is the only survey for that measuring moment (phase), the insertable survey cannot be inserted at the correct phase anymore. 

It could help if at the moment of insertion the phases are retreived from the track definition, not from the track(s) assigned to the patient.

**Comment by mennodekker** [comment]
The filter for the round description could be adjusted to include the current track definition and/or include deactivated rounds. It would also be nice if one could insert a new round description.
