### ISSUE TITLE
[feature request] Make email test language a choice

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#61]
**Reported by menno on 7 Sep 2015 08:53**

**Version:** 1.7.1

When testing email templates, the email is always sent in the english language. Make the language a clear choice or send in the currently selected language tab.

[Mantis Bugtracker #776](https://gemstracker.org/mantis/view.php?id=776)

**Comment by mennodekker** [comment]
After changing tabs the language is set correctly, but after loading the language is not set. This is due to the order of scripts firing.

**Comment by mddejong** [comment]
In the fix for #614 this is now fixed as well: the mail is send in currently selected language.
