### ISSUE TITLE
Add Url site management

### ISSUE THREAD

**Issue by mddejong** [GemsTracker/gemstracker-library#618]
Though most sites use one GT installation with a single Url, some have a more complicated setup. Pulse in particular, the Theta study made this a real problem.

In Pulse certain url's are accessible by certain organizations. At the moment we use a quite complicated mechanism using the gor_url_base Login url's field. (Elsewhere this is sometimes used to prevent having to select an organization during login.)

Another url that need to be stored is the **console.url** to enable sending mails from the command line. 

More url's are the **allowedSourceHosts** that can be set to enable putting a login form on a different site. If the allowedSourceHosts are not set then such a request will be refused as it will be seen as an attempt at a cross site attack.

The solution is to replace all these url's with their associated maintenance to a gems_sites table, that will be automatically filled and will enable the system administrators to set which url's allow access to which organizations. Using a priority field enables us to set the preferred url for an organization to use in mail's. (And if an organization does not have an url it will throw an error, but use of all-organization url's should prevent this from happening.)

This is a big change that influences a lot of code. Existing project should be able to run while the table does not exist, though it is ok if mailing is temporarily spotty.

**Comment by jvangestel** [comment]
superadmin logins with no set organization (login screens without organization, defaulting to \Gems_User_UserLoader::SYSTEM_NO_ORG ) fail to login, due to no allowed organization -1

**Comment by mddejong** [comment]
I'm writing the tests now, found some other stuff.
