### ISSUE TITLE
appointment changed by syncing should be logged in activity trail

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#633]
When a track is assigned and an appointment is made, surveys depending on this appointment will have opened and an invitation email will have been sent.
If the appointment is then changed to a later date by syncing with an external agenda app this could make the surveys open in the future. In the logs this is now an inconsistent state, as it cannot be traced in the activity log why an email has been sent (communication log) for surveys that open in the future.

**Comment by mddejong** [comment]
This is a EMC layer specific request. 

Additionally: version 2.0 of GemsTracker has the tools to make this easy.
