### ISSUE TITLE
[feature request] Add a default value field to track fields

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#64]
**Reported by Roel on 28 Sep 2015 14:17**

**Version:** 1.7.1

A track date field like birthdate in an elderly population needs another start value than next appointment. Choice of start year would be nice, but a more general solution would be to offer a default value for every type of track field.

[Mantis Bugtracker #782](https://gemstracker.org/mantis/view.php?id=782)

**Comment by roelfaber** [comment]
This issue not solved: default value created in track fields is not used in assigning and assigned tracks, the fields remain empty.
