### ISSUE TITLE
[bug] Survey sources - check status does not report the status but crashes if check fails.

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#65]
**Reported by Roel on 5 Nov 2015 16:12**

**Version:** 1.7.1

Status check (image A) leads to crash report (image B) if survey source privileges are  not met. Should be similar report like the one presented when synching surveys (image C).

**Steps to reproduce:** Create a survey source with wrong password. Then check its status.

[Mantis Bugtracker #786](https://gemstracker.org/mantis/view.php?id=786)

**Comment by mddejong** [comment]
Will show exception message instead of crash window
