### ISSUE TITLE
[documentation] Add/ post code which hides answer options in Lime Survey to GT site.

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#67]
**Reported by harm on 12 Nov 2015 09:29**

**Version:** 1.7.1

Jasper, could you?

[Mantis Bugtracker #788](https://gemstracker.org/mantis/view.php?id=788)

**Comment by mennodekker** [comment]
**Comment posted by harm on 12 Nov 2015 09:30**

please for 1.7.2.

**Comment by mddejong** [comment]
Solved using Javascript in LimeSurvey
