### ISSUE TITLE
[feature request] Add default track(s) to new respondents

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#68]
**Reported by Roel on 17 Nov 2015 15:35**

**Version:** 1.7.1

Add a select default field to tracks in parallel with organization selection. In this way a track can be default for one organization and not default for another.
After saving a new respondent add the track(s) that are assigned as default. A warning could indicate that track fields (like track end date ore custom track fields) are not filled in?

**Additional information:** In a simple track setup this can be a real time saver. For complex situations (multiple tracks, track fields etc) it should be handled with care.

[Mantis Bugtracker #789](https://gemstracker.org/mantis/view.php?id=789)

**Comment by mddejong** [comment]
This was solved in 1.8.6 with an after respondent change event at the Organisation level
