### ISSUE TITLE
Add index to gemsdata_responses

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#701]
For performance reasons (in our datawarehouse) I need an index in gemsdata_responses. Would it be possible to add it to the 1.9.1 branch / patch level so we can easily roll it out in Erasmus?

The statement would be the one below and it would fail if the index already exists. If I leave out the name of the index it will create a duplicate.

``` SQL
ALTER TABLE gemsdata__responses ADD INDEX gdr_changed (gdr_changed);
```

**Comment by jvangestel** [comment]
Also added in [5e73a47](https://github.com/GemsTracker/gemstracker-library/commit/5e73a4788820dfbdcbdc1f2394ca60ffd434ddbe)

**Comment by mennodekker** [comment]
I think it should be added to the file ```/configs/db_response_data/patches.sql``` since it could be in a different database.
