### ISSUE TITLE
Token overview by period creates an error

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#706]
Starting Overview - By Period generates a fatal error.

**Comment by roelfaber** [comment]
Might be due to an old server installation (PHP 5.6) and/or our custom layer.
Fatal error: Uncaught exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Subquery returns more than 1 row' in /data/www/lib/191p2/vendor/shardj/zf1-future/library/Zend/Db/Statement/Mysqli.php:214

**Comment by roelfaber** [comment]
Complete error message: 
Fatal error: Uncaught exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Subquery returns more than 1 row' in /data/www/lib/191p2/vendor/shardj/zf1-future/library/Zend/Db/Statement/Mysqli.php:214 Stack trace: #0 /data/www/lib/191p2/vendor/shardj/zf1-future/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array) #1 /data/www/lib/191p2/vendor/shardj/zf1-future/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array) #2 /data/www/lib/191p2/vendor/shardj/zf1-future/library/Zend/Db/Select.php(711): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select)) #3 /data/www/lib/191p2/vendor/magnafacta/mutil/src/MUtil/Db/Iterator/SelectIterator.php(95): Zend_Db_Select->query() #4 /data/www/lib/191p2/vendor/magnafacta/mutil/src/MUtil/Db/Iterator/SelectIterator.php(160): MUtil_Db_Iterator_SelectIterator->_initStatement() #5 [internal function]: MUtil_Db_Iterator_SelectIterator->rewind() #6 /data/www/lib/191p2/vendor/magnafacta/mutil/src/MUtil/Model/Model in /data/www/lib/191p2/vendor/shardj/zf1-future/library/Zend/Db/Statement/Mysqli.php on line 214

**Comment by mddejong** [comment]
This happens with an empty installation, so either the code does not take this situation into account or it is mysql version error.

**Comment by mddejong** [comment]
This error is caused by there not being any allowed organisations and this renders the select queries unreadable.

**Comment by mddejong** [comment]
Ho Roel,

 

 

Voor zover ik gezien heb, heb ik alles gefixed, m.u.v. de DossierExport PDF generatie. Ik heb in dat issue (https://github.com/GemsTracker/gemstracker-library/issues/708) wel wat toelichting gezet met mogelijke oorzaak en oplossingen.

 

De nieuwe release is deze geworden: https://github.com/GemsTracker/gemstracker-library/releases/tag/1.9.1-p5

 

 

Met vriendelijke groet,

Matijs de Jong

 

M +31 (0)6 21 543221

T +31 (0)10 8910902

Skype: matijsdejong

Teams: ***@***.*** ***@***.***> 

Zoom: ***@***.*** ***@***.***>
