### ISSUE TITLE
Export patient archive to pdf generates an error

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#708]
Export patient archives to pdf  generates a fatal error

**Comment by mddejong** [comment]
At the moment we cannot reproduce this. This problem may occur in an incorrectly configured installation e.g. one with an incorrect export.pdfExportCommand setting.

An alternative solution is to add to the require section of the composer.json the statement:        
   "phpoffice/phpword": "v0.18.*",
