### ISSUE TITLE
[bug] Question codes are case sensitive for survey_questions table

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#71]
**Reported by menno on 1 Feb 2016 11:15**

**Version:** 1.7.1

When using limesurvey as a source, the limesurvey internal question id is mapped to a question code whenever possible. This check is case sensitive, while the survey_questions table is case insensitive.

**Steps to reproduce:** Have two questions: instruction and Instruction, this will result in duplicate id error while syncing the survey.

**Additional information:** Sidenote: boilerplate questions are saved to the survey_questions table and the responses table. Since there are no responses at least the gemsdata__responses part seems unnecessary.

[Mantis Bugtracker #801](https://gemstracker.org/mantis/view.php?id=801)

**Comment by mddejong** [comment]
Does not seem to be a problem these days.
