### ISSUE TITLE
New site install default language not correct

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#714]
This refers to #618 and #655.
Installing a new site used to be default NL, is now EN (due to the default entry in the sites table?).
Correcting this afterwards always needs a server cache deletion before it works, not very nice.

**Comment by mddejong** [comment]
Gaat fout bij aanmaak in SiteUrl.php

**Comment by mddejong** [comment]
The code now sets the project locale correctly.
