### ISSUE TITLE
[bug] Export of numeric survey data is exported as strings

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#72]
**Reported by Roel on 10 Feb 2016 15:39**

**Version:** 1.7.1

LimeSurvey exports data with numeric values as numeric, in GemsTracker these exports are as strings (A64 in SPSS, but also as text in Excel).
   If SPSS can detect numeric or not, why not GemsTracker?

**Additional information:** Export of numeric gems data (like respondentid) is OK, although these ids never have decimals but get specified as F5.4 ().
Adding ALTER TYPE commands in SPSS syntax manually (ALTER TYPE PaFUI2QLQarray1_A (A64 = F4).) can be very tedious and time consuming. 

[Mantis Bugtracker #803](https://gemstracker.org/mantis/view.php?id=803)

**Comment by roelfaber** [comment]
Issue is not minor

**Comment by mennodekker** [comment]
Fixed in #335
