### ISSUE TITLE
Combining multiple codebooks in Excel of surveys with long names generates error - name too long

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#728]
See #515.
When combining surveys with long names this error is generated:

The sheet's name ("somequistionnairename_code-book") is invalid. It did not respect these rules:
 - It should not exceed 31 characters

Workaround: deselect surveys with long names, and export these separately one-by-one.

**Comment by mddejong** [comment]
Which version are we talking about? As 1.9.1p7 does have a check for this in the code.

**Comment by roelfaber** [comment]
So this was repaired in 1.9.1p7, and missed in the changelog? The problem was reported in p5, in p7 I can't reproduce the error anymore either.

**Comment by mddejong** [comment]
It was solved then but we did so under #515.
