### ISSUE TITLE
[bug] Advised limesurvey settings are incorrect

### ISSUE THREAD

**Issue by mennodekker** [GemsTracker/gemstracker-library#75]
**Reported by menno on 11 Mar 2016 08:25**

**Version:** 1.7.1

http://gemstracker.org/wiki/doku.php?id=userzone:userdoc:importing_questionnaires_in_gemstracker

allow edit after completion should NOT be set to yes

**Additional information:** Steps to take:
Update documentation
Update source sync script to find this problem
Possibly fix the problem automatically when needed

[Mantis Bugtracker #810](https://gemstracker.org/mantis/view.php?id=810)

**Comment by mennodekker** [comment]
Linked to #110

**Comment by mddejong** [comment]
We fixed this like ages ago.
