### ISSUE TITLE
export of open rosa data fails

### ISSUE THREAD

**Issue by roelfaber** [GemsTracker/gemstracker-library#94]
Version 1.7.1p6: when selecting (active or non-active) open rosa surveys for export, no records for export are reported and nothing is exported.  Workaround is direct export from database by database admin.

**Comment by mennodekker** [comment]
Export used to query the source and then add GemsTracker data. It now works the other way around so OpenRosa surveys without tokens can no longer be exported.
Due to the new way the export works, this functionality was lost. Let's see if we can restore it in some way.
